CREATE DATABASE SoftUni

USE SoftUni

CREATE TABLE Towns
(
	Id INT IDENTITY PRIMARY KEY,
	[Name] VARCHAR(30) NOT NULL
)

CREATE TABLE Addresses
(
	Id INT IDENTITY PRIMARY KEY,
	AddressText VARCHAR(100) NOT NULL,
	TownId INT NOT NULL
)

ALTER TABLE Addresses
ADD FOREIGN KEY (TownId) REFERENCES Towns(Id)

CREATE TABLE Departments
(
	Id INT IDENTITY PRIMARY KEY,
	[Name] VARCHAR(30) NOT NULL
)

CREATE TABLE Employees
(
	Id INT IDENTITY PRIMARY KEY,
	FirstName VARCHAR(30) NOT NULL,
	LastName VARCHAR(30) NOT NULL,
	JobTitle VARCHAR(30) NOT NULL,
	DepartmentId INT NOT NULL,
	HireDate DATETIME NOT NULL,
	Salary DECIMAL(15,2),
	AdressId INT NOT NULL
)

ALTER TABLE Employees
ADD CONSTRAINT FK_DepartmentId
FOREIGN KEY (DepartmentId) REFERENCES Departments(Id);

ALTER TABLE Employees
ADD CONSTRAINT FK_AdressId
FOREIGN KEY (AdressId) REFERENCES Addresses(Id);